import mongoose from 'mongoose';
import pino from 'pino';
import { PublishingMode } from '../../../models/content-operations/PublishingMode';

const logger = pino();

type Mode = 'manual' | 'approval' | 'autonomous';

export class AutomationModeEngine {
  async getMode(userId: mongoose.Types.ObjectId): Promise<{ mode: Mode; config: any }> {
    let modeDoc = await PublishingMode.findOne({ userId });
    if (!modeDoc) {
      modeDoc = await PublishingMode.create({ userId, mode: 'manual' });
    }
    return { mode: modeDoc.mode as Mode, config: modeDoc.config };
  }

  async setMode(userId: mongoose.Types.ObjectId, mode: Mode, reason?: string): Promise<{ mode: Mode; config: any }> {
    let modeDoc = await PublishingMode.findOne({ userId });
    if (!modeDoc) {
      modeDoc = new PublishingMode({ userId, mode });
    }

    const previousMode = modeDoc.mode;
    modeDoc.mode = mode;
    modeDoc.modeHistory.push({
      mode,
      activatedAt: new Date(),
      reason: reason || `Mode changed from ${previousMode} to ${mode}`,
    });

    switch (mode) {
      case 'manual':
        modeDoc.config.autoGenerateDrafts = true;
        modeDoc.config.autoSchedulePosts = false;
        modeDoc.config.autoPublishPosts = false;
        modeDoc.config.requiresReview = true;
        modeDoc.config.notifyBeforePublishing = true;
        break;
      case 'approval':
        modeDoc.config.autoGenerateDrafts = true;
        modeDoc.config.autoSchedulePosts = true;
        modeDoc.config.autoPublishPosts = false;
        modeDoc.config.requiresReview = true;
        modeDoc.config.notifyBeforePublishing = true;
        break;
      case 'autonomous':
        modeDoc.config.autoGenerateDrafts = true;
        modeDoc.config.autoSchedulePosts = true;
        modeDoc.config.autoPublishPosts = true;
        modeDoc.config.requiresReview = false;
        modeDoc.config.notifyBeforePublishing = false;
        modeDoc.config.notifyOnDraftReady = false;
        break;
    }

    await modeDoc.save();
    logger.info({ userId, mode, previousMode }, 'Publishing mode updated');

    return { mode: modeDoc.mode as Mode, config: modeDoc.config };
  }

  async updateConfig(userId: mongoose.Types.ObjectId, config: Partial<any>): Promise<any> {
    const modeDoc = await PublishingMode.findOneAndUpdate(
      { userId },
      { $set: Object.fromEntries(Object.entries(config).map(([k, v]) => [`config.${k}`, v])) },
      { new: true, upsert: true }
    );
    return modeDoc?.config;
  }

  shouldAutoAdvance(mode: Mode, currentStage: string): boolean {
    if (mode === 'autonomous') return true;
    if (mode === 'approval') {
      if (currentStage === 'draft_generated') return false;
      if (currentStage === 'approved') return true;
      if (currentStage === 'ready') return false;
      return false;
    }
    return false;
  }

  requiresReview(mode: Mode): boolean {
    return mode === 'manual' || mode === 'approval';
  }
}

export const automationModeEngine = new AutomationModeEngine();
