import mongoose, { Schema, Document, Model } from 'mongoose';

export interface IPublishingMode extends Document {
  userId: mongoose.Types.ObjectId;
  mode: 'manual' | 'approval' | 'autonomous';
  config: {
    autoGenerateDrafts: boolean;
    autoSchedulePosts: boolean;
    autoPublishPosts: boolean;
    requiresReview: boolean;
    notifyBeforePublishing: boolean;
    notifyOnDraftReady: boolean;
    preferredPublishTime: string;
    timezone: string;
    maxPostsPerDay: number;
    skipWeekends: boolean;
    autoArchiveAfterDays: number;
  };
  modeHistory: Array<{ mode: string; activatedAt: Date; reason: string }>;
  isActive: boolean;
  activatedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}

const PublishingModeSchema = new Schema<IPublishingMode>({
  userId: { type: Schema.Types.ObjectId, ref: 'User', required: true, index: true, unique: true },
  mode: { type: String, enum: ['manual', 'approval', 'autonomous'], default: 'manual' },
  config: {
    autoGenerateDrafts: { type: Boolean, default: true },
    autoSchedulePosts: { type: Boolean, default: false },
    autoPublishPosts: { type: Boolean, default: false },
    requiresReview: { type: Boolean, default: true },
    notifyBeforePublishing: { type: Boolean, default: true },
    notifyOnDraftReady: { type: Boolean, default: true },
    preferredPublishTime: { type: String, default: '09:00' },
    timezone: { type: String, default: 'UTC' },
    maxPostsPerDay: { type: Number, default: 1 },
    skipWeekends: { type: Boolean, default: false },
    autoArchiveAfterDays: { type: Number, default: 30 },
  },
  modeHistory: [{
    mode: String,
    activatedAt: { type: Date, default: Date.now },
    reason: { type: String, default: 'Initial setup' },
  }],
  isActive: { type: Boolean, default: true },
  activatedAt: { type: Date, default: Date.now },
}, {
  timestamps: true,
  collection: 'publishing_modes',
});

export const PublishingMode: Model<IPublishingMode> = mongoose.model<IPublishingMode>('PublishingMode', PublishingModeSchema);
export default PublishingMode;
